### ISSUE TITLE
Feature Request: Add support for vector string argument to URL

### ISSUE THREAD

**Issue by ViperGeek** [skontar/cvss-v4.0-calculator#1]
I'd like to be able to convey a specific CVSS v4.0 vector string using a tagged URL using the calculator.  For example:

[CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:H/E:P/R:A/V:C/U:Red](https://skontar.github.io/cvss-v4.0-calculator#CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:H/E:P/R:A/V:C/U:Red)

Please consider supporting the ability to provide an argument to the URL, similar to:

<https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H>

**Comment by skontar** [comment]
Added in 11b600e. Your provided link should now be working.

**Comment by ViperGeek** [comment]
***Incredible!***  Thank you very much.

Happy Holidays 🎄
