### ISSUE TITLE
Specific Vector Crashes Calculator

### ISSUE THREAD

**Issue by petermell** [skontar/cvss-v4.0-calculator#16]
This metric value set crashes the calculator:

https://skontar.github.io/cvss-v4.0-calculator/#CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:A/CR:M/IR:H/AR:M/MVI:H/MSI:H/MSA:S

Here is another one:
https://skontar.github.io/cvss-v4.0-calculator/#CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:A/CR:H/IR:M/AR:M/MVI:H/MSI:S/MSA:S

**Comment by skontar** [comment]
Good catch. My mistake, I did not notice that the new CSV file has only one line header and my conversion script missed macro vector `000000`. 

Fixed in [0552e38](https://github.com/skontar/cvss-v4.0-calculator/commit/0552e3864c01f036f9a163c6e79eb2e9b797d43c).
