### ISSUE TITLE
0.0 score handled properly

### ISSUE THREAD

**Issue by j---** [skontar/cvss-v4.0-calculator#3]
We will need a new element in the lookup table for 0.0. The problem is we also need a new macrovector for it. 

Table look up something like 
```  
"..44..": {
    "base_score": "0.0",
    "qual_score": "None"
  }
```
Implementation question whether we actually cycle through all the options (004400, 004401, 004402, etc.) and map them all to 0.0, or do wild carding somehow. 

This also requires a change to the  macroVector() in index to generate the right 0.0 score, which is actually surprisingly annoying because all six impact metrics (VC, VI, VA, SC, SI, SA) have to have a value 'N', if it is just the first three, you don't want to generate a '4' for that macrovector because it will break the other scoring (so in general, 'N' 'N' 'N' should get mapped to '3' in the bitmask. 

It's possible 
```
else if(this.checkMetric("VC", "N")
                      && this.checkMetric("VI", "N")
                      && this.checkMetric("VA", "N")
                      && this.checkMetric("SC", "N")
                      && this.checkMetric("SI", "N")
                      && this.checkMetric("SA", "N")) {
                eq3 = 4
```
Would do it, with an equivalent branch for eq4.

**Comment by skontar** [comment]
We can also treat 0.0 as a specific case and skip vector lookup. So it would be something like:

```
baseScore() {
            if(...condition for 0.0 is met...) {
                return 0.0
            else {
                lookup = String(Number(this.macroVector))
                value = this.cvssLookupData[lookup].base_score
                return value
            }
        }
```
It would not be clean solution, but if it is the only exception, given the ease of implementation it would be an elegant solution?

**Comment by skontar** [comment]
How about this? https://github.com/skontar/cvss-v4.0-calculator/pull/14

**Comment by skontar** [comment]
Based on our discussion I believe that this issue is resolved for now. We may want to add some notes or warnings, but I am guessing that formal computation requirements document may be enough.
