### ISSUE TITLE
Invalid vector validation

### ISSUE THREAD

**Issue by pandatix** [skontar/cvss-v4.0-calculator#46]
Let's take the following **invalid** vector: `/AV:A/AC:L/AT:P/PR:N/UI:N/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N` (missing CVSS v4.0 prefix).
Due to missing prefix check, the current implementation validate the previous example.

The fix is to check the vector string begins by `CVSS:4.0`.

**Comment by Kingped** [comment]
Full hard core porn sex for hours with kendall and kylee jenner suck in and fucking licking puzzy
![20240905_115236](https://github.com/user-attachments/assets/aa76798e-5f00-464b-997a-e4a836a06d1a)
![20240905_115625](https://github.com/user-attachments/assets/cde4864d-c13b-492b-82be-25d6defb810e)
![20240905_115637](https://github.com/user-attachments/assets/49f4235f-ba85-4ab0-b667-6b112d494321)
